package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Anexo generated by hbm2java
 */
@Entity
@Table(name = "Anexo", schema = "dbo", catalog = "Unisolicitacao")
public class Anexo implements java.io.Serializable {

	private Integer idSolicitacao;
	private Solicitacao solicitacao;
	private String tipoAnexado;
	private Clob conteudoDoAnexo;
	private String nomeDoAnexo;

	public Anexo() {
	}

	public Anexo(Solicitacao solicitacao, String tipoAnexado,
			Clob conteudoDoAnexo, String nomeDoAnexo) {
		this.solicitacao = solicitacao;
		this.tipoAnexado = tipoAnexado;
		this.conteudoDoAnexo = conteudoDoAnexo;
		this.nomeDoAnexo = nomeDoAnexo;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "solicitacao"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdSolicitacao", unique = true, nullable = false)
	public Integer getIdSolicitacao() {
		return this.idSolicitacao;
	}

	public void setIdSolicitacao(Integer idSolicitacao) {
		this.idSolicitacao = idSolicitacao;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Solicitacao getSolicitacao() {
		return this.solicitacao;
	}

	public void setSolicitacao(Solicitacao solicitacao) {
		this.solicitacao = solicitacao;
	}

	@Column(name = "TipoAnexado", nullable = false, length = 10)
	public String getTipoAnexado() {
		return this.tipoAnexado;
	}

	public void setTipoAnexado(String tipoAnexado) {
		this.tipoAnexado = tipoAnexado;
	}

	@Column(name = "ConteudoDoAnexo", nullable = false)
	public Clob getConteudoDoAnexo() {
		return this.conteudoDoAnexo;
	}

	public void setConteudoDoAnexo(Clob conteudoDoAnexo) {
		this.conteudoDoAnexo = conteudoDoAnexo;
	}

	@Column(name = "NomeDoAnexo", nullable = false)
	public String getNomeDoAnexo() {
		return this.nomeDoAnexo;
	}

	public void setNomeDoAnexo(String nomeDoAnexo) {
		this.nomeDoAnexo = nomeDoAnexo;
	}

}
