package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Avaliacao generated by hbm2java
 */
@Entity
@Table(name = "Avaliacao", schema = "dbo", catalog = "Unisolicitacao")
public class Avaliacao implements java.io.Serializable {

	private Integer idAvaliacao;
	private Atendimento atendimento;
	private Clob comentario;
	private Short nota;
	private Date dataHora;

	public Avaliacao() {
	}

	public Avaliacao(Integer idAvaliacao, Atendimento atendimento, Clob comentario,
			Short nota, Date dataHora) {
		this.idAvaliacao = idAvaliacao;
		this.atendimento = atendimento;
		this.comentario = comentario;
		this.nota = nota;
		this.dataHora = dataHora;
	}

	@Id
	@Column(name = "idAvaliacao", unique = true, nullable = false)
	public Integer getIdAvaliacao() {
		return this.idAvaliacao;
	}

	public void setIdAvaliacao(Integer idAvaliacao) {
		this.idAvaliacao = idAvaliacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdAtendimento", nullable = false)
	public Atendimento getAtendimento() {
		return this.atendimento;
	}

	public void setAtendimento(Atendimento atendimento) {
		this.atendimento = atendimento;
	}

	@Column(name = "Comentario", nullable = false)
	public Clob getComentario() {
		return this.comentario;
	}

	public void setComentario(Clob comentario) {
		this.comentario = comentario;
	}

	@Column(name = "Nota", nullable = false)
	public Short getNota() {
		return this.nota;
	}

	public void setNota(Short nota) {
		this.nota = nota;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataHora", nullable = false, length = 23)
	public Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}

}
