package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Conversa generated by hbm2java
 */
@Entity
@Table(name = "conversa", schema = "dbo", catalog = "Unisolicitacao")
public class Conversa implements java.io.Serializable {

	private ConversaId id;
	private Atendimento atendimento;
	private Solicitacao solicitacao;

	public Conversa() {
	}

	public Conversa(ConversaId id, Atendimento atendimento,
			Solicitacao solicitacao) {
		this.id = id;
		this.atendimento = atendimento;
		this.solicitacao = solicitacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idAtendimento", column = @Column(name = "IdAtendimento", nullable = false)),
			@AttributeOverride(name = "idSolicitacao", column = @Column(name = "IdSolicitacao", nullable = false)),
			@AttributeOverride(name = "dataConversa", column = @Column(name = "dataConversa", nullable = false, length = 23)),
			@AttributeOverride(name = "mensagem", column = @Column(name = "mensagem", nullable = false)) })
	public ConversaId getId() {
		return this.id;
	}

	public void setId(ConversaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdAtendimento", nullable = false, insertable = false, updatable = false)
	public Atendimento getAtendimento() {
		return this.atendimento;
	}

	public void setAtendimento(Atendimento atendimento) {
		this.atendimento = atendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSolicitacao", nullable = false, insertable = false, updatable = false)
	public Solicitacao getSolicitacao() {
		return this.solicitacao;
	}

	public void setSolicitacao(Solicitacao solicitacao) {
		this.solicitacao = solicitacao;
	}

}
