package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConversaId generated by hbm2java
 */
@Embeddable
public class ConversaId implements java.io.Serializable {

	private Integer idAtendimento;
	private Integer idSolicitacao;
	private Date dataConversa;
	private String mensagem;

	public ConversaId() {
	}

	public ConversaId(Integer idAtendimento, Integer idSolicitacao, Date dataConversa,
			String mensagem) {
		this.idAtendimento = idAtendimento;
		this.idSolicitacao = idSolicitacao;
		this.dataConversa = dataConversa;
		this.mensagem = mensagem;
	}

	@Column(name = "IdAtendimento", nullable = false)
	public Integer getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(Integer idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	@Column(name = "IdSolicitacao", nullable = false)
	public Integer getIdSolicitacao() {
		return this.idSolicitacao;
	}

	public void setIdSolicitacao(Integer idSolicitacao) {
		this.idSolicitacao = idSolicitacao;
	}

	@Column(name = "dataConversa", nullable = false, length = 23)
	public Date getDataConversa() {
		return this.dataConversa;
	}

	public void setDataConversa(Date dataConversa) {
		this.dataConversa = dataConversa;
	}

	@Column(name = "mensagem", nullable = false)
	public String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConversaId))
			return false;
		ConversaId castOther = (ConversaId) other;

		return (this.getIdAtendimento() == castOther.getIdAtendimento())
				&& (this.getIdSolicitacao() == castOther.getIdSolicitacao())
				&& ((this.getDataConversa() == castOther.getDataConversa()) || (this
						.getDataConversa() != null
						&& castOther.getDataConversa() != null && this
						.getDataConversa().equals(castOther.getDataConversa())))
				&& ((this.getMensagem() == castOther.getMensagem()) || (this
						.getMensagem() != null
						&& castOther.getMensagem() != null && this
						.getMensagem().equals(castOther.getMensagem())));
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getIdAtendimento();
		result = 37 * result + this.getIdSolicitacao();
		result = 37
				* result
				+ (getDataConversa() == null ? 0 : this.getDataConversa()
						.hashCode());
		result = 37 * result
				+ (getMensagem() == null ? 0 : this.getMensagem().hashCode());
		return result;
	}

}
