package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fechamento generated by hbm2java
 */
@Entity
@Table(name = "Fechamento", schema = "dbo", catalog = "Unisolicitacao")
public class Fechamento implements java.io.Serializable {

	private Integer idFechamento;
	private Solicitacao solicitacao;
	private String desrição;
	private Date dataFechamento;

	public Fechamento() {
	}

	public Fechamento(Integer idFechamento, Solicitacao solicitacao, String desrição) {
		this.idFechamento = idFechamento;
		this.solicitacao = solicitacao;
		this.desrição = desrição;
	}

	public Fechamento(Integer idFechamento, Solicitacao solicitacao,
			String desrição, Date dataFechamento) {
		this.idFechamento = idFechamento;
		this.solicitacao = solicitacao;
		this.desrição = desrição;
		this.dataFechamento = dataFechamento;
	}

	@Id
	@Column(name = "idFechamento", unique = true, nullable = false)
	public Integer getIdFechamento() {
		return this.idFechamento;
	}

	public void setIdFechamento(Integer idFechamento) {
		this.idFechamento = idFechamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dSolicitacao", nullable = false)
	public Solicitacao getSolicitacao() {
		return this.solicitacao;
	}

	public void setSolicitacao(Solicitacao solicitacao) {
		this.solicitacao = solicitacao;
	}

	@Column(name = "desrição", nullable = false, length = 1000)
	public String getDesrição() {
		return this.desrição;
	}

	public void setDesrição(String desrição) {
		this.desrição = desrição;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataFechamento", length = 23)
	public Date getDataFechamento() {
		return this.dataFechamento;
	}

	public void setDataFechamento(Date dataFechamento) {
		this.dataFechamento = dataFechamento;
	}

}
