package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prioridade generated by hbm2java
 */
@Entity
@Table(name = "Prioridade", schema = "dbo", catalog = "Unisolicitacao")
public class Prioridade implements java.io.Serializable {

	private Short idPrioridade;
	private String descricao;
	private Set<Solicitacao> solicitacaos = new HashSet<Solicitacao>(0);

	public Prioridade() {
	}

	public Prioridade(Short idPrioridade, String descricao) {
		this.idPrioridade = idPrioridade;
		this.descricao = descricao;
	}

	public Prioridade(Short idPrioridade, String descricao,
			Set<Solicitacao> solicitacaos) {
		this.idPrioridade = idPrioridade;
		this.descricao = descricao;
		this.solicitacaos = solicitacaos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IdPrioridade", unique = true, nullable = false)
	public Short getIdPrioridade() {
		return this.idPrioridade;
	}

	public void setIdPrioridade(Short idPrioridade) {
		this.idPrioridade = idPrioridade;
	}

	@Column(name = "Descricao", nullable = false, length = 30)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prioridade")
	public Set<Solicitacao> getSolicitacaos() {
		return this.solicitacaos;
	}

	public void setSolicitacaos(Set<Solicitacao> solicitacaos) {
		this.solicitacaos = solicitacaos;
	}

}
