package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SistemaModulo generated by hbm2java
 */
@Entity
@Table(name = "SistemaModulo", schema = "dbo", catalog = "Unisolicitacao")
public class SistemaModulo implements java.io.Serializable {

	private Integer idSistema;
	private Sistema sistema;
	private String nome;
	private Set<Solicitacao> solicitacaos = new HashSet<Solicitacao>(0);

	public SistemaModulo() {
	}

	public SistemaModulo(Sistema sistema, String nome, Integer idSolicitacao) {
		this.sistema = sistema;
		this.nome = nome;
	}

	public SistemaModulo(Sistema sistema, String nome, Integer idSolicitacao,
			Set<Solicitacao> solicitacaos) {
		this.sistema = sistema;
		this.nome = nome;
		this.solicitacaos = solicitacaos;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "sistema"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdSistema", unique = true, nullable = false)
	public Integer getIdSistema() {
		return this.idSistema;
	}

	public void setIdSistema(Integer idSistema) {
		this.idSistema = idSistema;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@Column(name = "Nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistemaModulo")
	public Set<Solicitacao> getSolicitacaos() {
		return this.solicitacaos;
	}

	public void setSolicitacaos(Set<Solicitacao> solicitacaos) {
		this.solicitacaos = solicitacaos;
	}

}
