package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Sistema generated by hbm2java
 */
@Entity
@Table(name = "Sistema", schema = "dbo", catalog = "Unisolicitacao")
public class Sistema implements java.io.Serializable {

	private Integer codigoDoSistemaNoUniseguranca;
	private String nome;

	public Sistema() {
	}

	public Sistema(Integer codigoDoSistemaNoUniseguranca, Integer idSolicitacao) {
		this.codigoDoSistemaNoUniseguranca = codigoDoSistemaNoUniseguranca;
	}

	public Sistema(Integer codigoDoSistemaNoUniseguranca, String nome,
			Integer idSolicitacao, SistemaModulo sistemaModulo) {
		this.codigoDoSistemaNoUniseguranca = codigoDoSistemaNoUniseguranca;
		this.nome = nome;
	}

	@Id
	@Column(name = "CodigoDoSistemaNoUniseguranca", unique = true, nullable = false)
	public Integer getCodigoDoSistemaNoUniseguranca() {
		return this.codigoDoSistemaNoUniseguranca;
	}

	public void setCodigoDoSistemaNoUniseguranca(
			Integer codigoDoSistemaNoUniseguranca) {
		this.codigoDoSistemaNoUniseguranca = codigoDoSistemaNoUniseguranca;
	}

	@Column(name = "Nome", length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
}
