package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Situacao generated by hbm2java
 */
@Entity
@Table(name = "Situacao", schema = "dbo", catalog = "Unisolicitacao")
public class Situacao implements java.io.Serializable {

	private Short idSituacao;
	private String descricao;
	private Set<Solicitacao> solicitacaos = new HashSet<Solicitacao>(0);

	public Situacao() {
	}

	public Situacao(Short idSituacao, String descricao) {
		this.idSituacao = idSituacao;
		this.descricao = descricao;
	}

	public Situacao(Short idSituacao, String descricao,
			Set<Solicitacao> solicitacaos) {
		this.idSituacao = idSituacao;
		this.descricao = descricao;
		this.solicitacaos = solicitacaos;
	}

	@Id
	@Column(name = "IdSituacao", unique = true, nullable = false)
	public Short getIdSituacao() {
		return this.idSituacao;
	}

	public void setIdSituacao(Short idSituacao) {
		this.idSituacao = idSituacao;
	}

	@Column(name = "Descricao", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "situacao")
	public Set<Solicitacao> getSolicitacaos() {
		return this.solicitacaos;
	}

	public void setSolicitacaos(Set<Solicitacao> solicitacaos) {
		this.solicitacaos = solicitacaos;
	}

}
