package unisolicitacao.business;

// Generated 29/04/2014 16:22:41 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitacao generated by hbm2java
 */
@Entity
@Table(name = "Solicitacao ", schema = "dbo", catalog = "Unisolicitacao")
public class Solicitacao implements java.io.Serializable {

	private Integer idSolicitacao;
	private Situacao situacao;
	private Setor setorByIdSetorDestino;
	private Setor setorByIdSetorOrigem;
	private Prioridade prioridade;
	private SistemaModulo sistemaModulo;
	private Usuario usuario;
	private String descAssunto;
	private String descProblema;
	private Date dataSolicitacao;
	private Date dataDesejada;
	private List<Anexo> anexos = new ArrayList<Anexo>();
	private Set<Atendimento> atendimentos = new HashSet<Atendimento>(0);
	private Set<Conversa> conversas = new HashSet<Conversa>(0);
	private Set<Fechamento> fechamentos = new HashSet<Fechamento>(0);

	public Solicitacao() {
	}

	public Solicitacao(Integer idSolicitacao,
			Situacao situacao, Prioridade prioridade,
			SistemaModulo sistemaModulo, Usuario usuario, String descAssunto,
			String descProblema, Date dataSolicitacao) {
		this.idSolicitacao = idSolicitacao;
		this.situacao = situacao;
		this.prioridade = prioridade;
		this.sistemaModulo = sistemaModulo;
		this.usuario = usuario;
		this.descAssunto = descAssunto;
		this.descProblema = descProblema;
		this.dataSolicitacao = dataSolicitacao;
	}

	public Solicitacao(Integer idSolicitacao,
			Situacao situacao, Setor setorByIdSetorDestino,
			Setor setorByIdSetorOrigem, Prioridade prioridade,
			SistemaModulo sistemaModulo, Usuario usuario, String descAssunto,
			String descProblema, Date dataSolicitacao, Date dataDesejada,
			List<Anexo> anexos, Set<Atendimento> atendimentos,
			Set<Conversa> conversas, Set<Solicitacao> solicitacaos,
			Set<Fechamento> fechamentos) {
		this.idSolicitacao = idSolicitacao;
		this.situacao = situacao;
		this.setorByIdSetorDestino = setorByIdSetorDestino;
		this.setorByIdSetorOrigem = setorByIdSetorOrigem;
		this.prioridade = prioridade;
		this.sistemaModulo = sistemaModulo;
		this.usuario = usuario;
		this.descAssunto = descAssunto;
		this.descProblema = descProblema;
		this.dataSolicitacao = dataSolicitacao;
		this.dataDesejada = dataDesejada;
		this.anexos = anexos;
		this.atendimentos = atendimentos;
		this.conversas = conversas;
		this.fechamentos = fechamentos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IdSolicitacao", unique = true, nullable = false)
	public Integer getIdSolicitacao() {
		return this.idSolicitacao;
	}

	public void setIdSolicitacao(Integer idSolicitacao) {
		this.idSolicitacao = idSolicitacao;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSituacao", nullable = false)
	public Situacao getSituacao() {
		return this.situacao;
	}

	public void setSituacao(Situacao situacao) {
		this.situacao = situacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSetorDestino", nullable = false)
	public Setor getSetorByIdSetorDestino() {
		return this.setorByIdSetorDestino;
	}

	public void setSetorByIdSetorDestino(Setor setorByIdSetorDestino) {
		this.setorByIdSetorDestino = setorByIdSetorDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSetorOrigem")
	public Setor getSetorByIdSetorOrigem() {
		return this.setorByIdSetorOrigem;
	}

	public void setSetorByIdSetorOrigem(Setor setorByIdSetorOrigem) {
		this.setorByIdSetorOrigem = setorByIdSetorOrigem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPrioridade"/*, nullable = false*/)
	public Prioridade getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(Prioridade prioridade) {
		this.prioridade = prioridade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSistema", nullable = false)
	public SistemaModulo getSistemaModulo() {
		return this.sistemaModulo;
	}

	public void setSistemaModulo(SistemaModulo sistemaModulo) {
		this.sistemaModulo = sistemaModulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "DescAssunto", nullable = false)
	public String getDescAssunto() {
		return this.descAssunto;
	}

	public void setDescAssunto(String descAssunto) {
		this.descAssunto = descAssunto;
	}

	@Column(name = "DescProblema", nullable = false)
	public String getDescProblema() {
		return this.descProblema;
	}

	public void setDescProblema(String descProblema) {
		this.descProblema = descProblema;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataSolicitacao", nullable = false, length = 23)
	public Date getDataSolicitacao() {
		return this.dataSolicitacao;
	}

	public void setDataSolicitacao(Date dataSolicitacao) {
		this.dataSolicitacao = dataSolicitacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataDesejada", length = 23)
	public Date getDataDesejada() {
		return this.dataDesejada;
	}

	public void setDataDesejada(Date dataDesejada) {
		this.dataDesejada = dataDesejada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitacao")
	public List<Anexo> getAnexos() {
		return this.anexos;
	}

	public void setAnexos(List<Anexo> anexos) {
		this.anexos = anexos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitacao")
	public Set<Atendimento> getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos(Set<Atendimento> atendimentos) {
		this.atendimentos = atendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitacao")
	public Set<Conversa> getConversas() {
		return this.conversas;
	}

	public void setConversas(Set<Conversa> conversas) {
		this.conversas = conversas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitacao")
	public Set<Fechamento> getFechamentos() {
		return this.fechamentos;
	}

	public void setFechamentos(Set<Fechamento> fechamentos) {
		this.fechamentos = fechamentos;
	}

}
